version: "3.9"

services:
  # Application React
  front:
    build: ./platform/front
    container_name: obrail_front
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

  # API REST FastAPI
  api:
    build: ./platform/server
    container_name: obrail_api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=obrail
      - DB_USER=obrail_user
      - DB_PASSWORD=1234
      - JWT_SECRET=supersecretkey
    depends_on:
      - db
    restart: always

  # Base de données PostgreSQL
  db:
    image: postgres:15
    container_name: obrail_db
    restart: always
    environment:
      POSTGRES_USER: obrail_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: obrail
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  etl:
    build:
      context: ./etl           # contexte = dossier etl
      dockerfile: Dockerfile.etl
    container_name: obrail_etl
    depends_on:
      - db
      - api
      - front
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=obrail
      - DB_USER=obrail_user
      - DB_PASSWORD=1234
    volumes:
      - ./etl:/app/etl        
      - ./data:/app/data       
    command: >
      sh -c "echo 'Démarrage de l ETL...' &&
            python /app/etl/run_full_etl.py"
    restart: "no"

  prometheus:
      image: prom/prometheus
      container_name: obrail_prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: obrail_grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:latest
    container_name: obrail_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/local-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: obrail_promtail
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  db_data:
