"""
Configuration pour la transformation des données - Version non destructive
"""
import os
from pathlib import Path

# Chemins
PROJECT_ROOT = Path(__file__).parent.parent.parent
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
DATA_WAREHOUSE = PROJECT_ROOT / "data" / "warehouse"

# Création des dossiers
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
DATA_WAREHOUSE.mkdir(parents=True, exist_ok=True)

# Stratégie de nettoyage
CLEANING_STRATEGY = {
    'missing_values': 'impute_or_flag',  # Options: impute, flag, keep
    'duplicates': 'flag',  # Options: remove, flag, keep
    'outliers': 'flag',  # Options: remove, flag, keep
    'inconsistencies': 'correct_when_possible'  # Options: correct, flag, keep
}

# Mapping des pays
COUNTRY_CODES = {
    "FR": "France",
    "CH": "Suisse",
    "DE": "Allemagne",
    "AT": "Autriche",
    "IT": "Italie",
    "ES": "Espagne",
    "UK": "Royaume-Uni",
    "BE": "Belgique",
    "NL": "Pays-Bas",
    "PL": "Pologne",
    "CZ": "République Tchèque",
    "HU": "Hongrie",
    "RO": "Roumanie",
    "SK": "Slovaquie",
    "SI": "Slovénie",
    "HR": "Croatie",
    "BG": "Bulgarie",
    "GR": "Grèce",
    "PT": "Portugal",
    "SE": "Suède",
    "NO": "Norvège",
    "FI": "Finlande",
    "DK": "Danemark",
    "IE": "Irlande",
    "LU": "Luxembourg",
    "MT": "Malte",
    "CY": "Chypre",
    "EE": "Estonie",
    "LV": "Lettonie",
    "LT": "Lituanie",
    "ME": "Monténégro",
    "RS": "Serbie",
    "MK": "Macédoine du Nord",
    "AL": "Albanie",
    "BA": "Bosnie-Herzégovine",
    "XK": "Kosovo",
    "MD": "Moldavie",
    "UA": "Ukraine",
    "BY": "Biélorussie",
    "GE": "Géorgie",
    "AM": "Arménie",
    "AZ": "Azerbaïdjan",
    "TR": "Turquie",
    "IL": "Israël",
    "MA": "Maroc",
    "TN": "Tunisie",
    "DZ": "Algérie",
    "EG": "Égypte",
    "LB": "Liban",
    "JO": "Jordanie",
    "SY": "Syrie",
    "IQ": "Irak",
    "IR": "Iran",
    "SA": "Arabie Saoudite",
    "YE": "Yémen",
    "OM": "Oman",
    "AE": "Émirats Arabes Unis",
    "QA": "Qatar",
    "KW": "Koweït",
    "BH": "Bahreïn",
    "IN": "Inde",
    "PK": "Pakistan",
    "BD": "Bangladesh",
    "LK": "Sri Lanka",
    "NP": "Népal",
    "BT": "Bhoutan",
    "MV": "Maldives",
    "MM": "Myanmar",
    "TH": "Thaïlande",
    "LA": "Laos",
    "KH": "Cambodge",
    "VN": "Vietnam",
    "MY": "Malaisie",
    "SG": "Singapour",
    "ID": "Indonésie",
    "PH": "Philippines",
    "BN": "Brunei",
    "TL": "Timor oriental",
    "CN": "Chine",
    "JP": "Japon",
    "KR": "Corée du Sud",
    "KP": "Corée du Nord",
    "MN": "Mongolie",
    "TW": "Taïwan",
    "HK": "Hong Kong",
    "MO": "Macao",
    "AU": "Australie",
    "NZ": "Nouvelle-Zélande",
    "PG": "Papouasie-Nouvelle-Guinée",
    "FJ": "Fidji",
    "SB": "Îles Salomon",
    "VU": "Vanuatu",
    "NC": "Nouvelle-Calédonie",
    "PF": "Polynésie française",
    "WS": "Samoa",
    "TO": "Tonga",
    "KI": "Kiribati",
    "TV": "Tuvalu",
    "NR": "Nauru",
    "FM": "Micronésie",
    "MH": "Îles Marshall",
    "PW": "Palaos",
    "CA": "Canada",
    "US": "États-Unis",
    "MX": "Mexique",
    "GT": "Guatemala",
    "BZ": "Belize",
    "SV": "Salvador",
    "HN": "Honduras",
    "NI": "Nicaragua",
    "CR": "Costa Rica",
    "PA": "Panama",
    "CU": "Cuba",
    "DO": "République dominicaine",
    "HT": "Haïti",
    "JM": "Jamaïque",
    "TT": "Trinité-et-Tobago",
    "BB": "Barbade",
    "GD": "Grenade",
    "VC": "Saint-Vincent-et-les-Grenadines",
    "LC": "Sainte-Lucie",
    "KN": "Saint-Christophe-et-Niévès",
    "AG": "Antigua-et-Barbuda",
    "DM": "Dominique",
    "BS": "Bahamas",
    "CO": "Colombie",
    "VE": "Venezuela",
    "GY": "Guyana",
    "SR": "Suriname",
    "GF": "Guyane française",
    "EC": "Équateur",
    "PE": "Pérou",
    "BO": "Bolivie",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "AR": "Argentine",
    "CL": "Chili",
    "BR": "Brésil",
}