FROM python:3.9-slim

WORKDIR /app

# Copie du fichier des dépendances (présent dans le même dossier)
COPY requirements-etl.txt .

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements-etl.txt

# Les scripts ETL seront montés via volume au moment de l'exécution